<?php
use Laminas\Http\Client;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
  $type = $template->label();
else:
  $type = "";
endif;

$main = $this->resourcePageBlocks($item, 'main')->hasBlocks();
$right = $this->resourcePageBlocks($item, 'right')->hasBlocks();
$left = $this->resourcePageBlocks($item, 'left')->hasBlocks();
$second = $this->resourcePageBlocks($item, 'second')->hasBlocks();
?>
<style>
  a {
    text-decoration: none;
  }
</style>
<div class="container">
  <div >
    <div id="portal-breadcrumbs" class="breadcrumbs" style="display:block;">
      <span class="breadcrumb-item">
          <a href="<?php echo $site->url();?>">Home</a>
      </span>

      <?php if($type == 'News'):?>
        <span class="breadcrumb-item" dir="ltr">
          <a href="<?php echo $site->url()."/page/news";?>">News</a>
        </span>
      <?php else:?>
        <span class="breadcrumb-item">
          <a href="<?php echo $site->url()."/search";?>">Catalogue</a>         
        </span>    
      <?php endif;?>
      <span class="breadcrumb-item active">
        <?php echo $item->displayTitle(); ?>
      </span>

    </div>
  </div>
 
  <h1><?php echo $item->displayTitle(); ?></h1>
  <?php if($main && $right && $left): ?>
  <div class="row">
  <div class="left-content col-md-3">
      <?php echo $this->resourcePageBlocks($item, 'left')->getBlocks(); ?>
    </div>
    <div class="main-content col-md-6">
      <?php echo $this->resourcePageBlocks($item, 'main')->getBlocks(); ?>
    </div>
    <div class="right-content col-md-3">
      <?php echo $this->resourcePageBlocks($item, 'right')->getBlocks(); ?>
    </div>
  </div>
<?php endif; ?>
<?php if($main && $right && !$left): ?>
  <div class="row">
    <div class="main-content col-md-8">
      <?php echo $this->resourcePageBlocks($item, 'main')->getBlocks(); ?>
    </div>
    <div class="right-content col-md-4">
      <?php echo $this->resourcePageBlocks($item, 'right')->getBlocks(); ?>
    </div>
  </div>
<?php endif; ?>
<?php if($main && !$right && $left): ?>
  <div class="row">
  <div class="left-content col-md-4">
      <?php echo $this->resourcePageBlocks($item, 'left')->getBlocks(); ?>
    </div>
    <div class="main-content col-md-8">
      <?php echo $this->resourcePageBlocks($item, 'main')->getBlocks(); ?>
    </div>
  </div>
<?php endif; ?>
<?php if($main && !$right && !$left): ?>
  <div class="row">
    <div class="main-content col-md-12">
      <?php echo $this->resourcePageBlocks($item, 'main')->getBlocks(); ?>
    </div>
  </div>
<?php endif; ?>
<?php if($second): ?>
  <div class="row">
    <div class="second-content col-md-12">
      <?php echo $this->resourcePageBlocks($item, 'second')->getBlocks(); ?>
    </div>
  </div>
<?php endif; ?>
</div>

