version: '3'

services:
  omeka-s:
    image: omeka_s_v4:latest
    ports:
      - "9003:80"   
    volumes:
      - ./modules/:/var/www/html/test/modules/
      - ./themes/:/var/www/html/test/themes/
      - ./files/:/var/www/html/test/files/
      - ./config/:/var/www/html/test/config/
      - ./htaccess:/var/www/html/test/.htaccess
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    restart: "no"
