services:
  omeka-s:
    build: ./
    networks:
     - my-network
    ports:
    ports:
      - "9003:80"   
    volumes:
      - ./modules/:/var/www/html/virtuele-leeszalen/modules/
      - ./themes/:/var/www/html/virtuele-leeszalen/themes/
      - ./files/:/var/www/html/virtuele-leeszalen/files/
      - ./config/:/var/www/html/virtuele-leeszalen/config/
    restart: "no"
    
networks:
  my-network:
    external:
      name: dev-network