<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = ($options['mode'] ?? '') === 'link';
$displayCount = !empty($options['display_count']);
?>

<ul class="search-facet-items">
    <?php foreach (array_slice($facetValues,0,8) as $facetValue):
        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = $name . '[]' . $escapedValue;
        if($facetValue['label'] == "Yes"):
            $facetValue['label'] = "Ja";
        endif;    
        if($facetValue['label'] == "Collection focus"):
            $facetValue['label'] = "Collectiefocus";
        endif;  
        if($facetValue['label'] == "Institution collection"):
            $facetValue['label'] = "Institutiecollectie";
        endif; 
        if($facetValue['label'] == "Sub-collection"):
            $facetValue['label'] = "Deelcollectie";
        endif; 
        $label = $displayCount
            ? sprintf('%s (<span class="count">%d</span>)', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
    ?>
    <li class="search-facet-item">
        <input type="checkbox" name="facet[<?= $name ?>][]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label for="<?= $escapedId ?>"><?= $label ?></label>
    </li>
    <?php endforeach; ?>
    <?php if(sizeof($facetValues)>8):?>                
        <div class="more-link"><a class="has-text-grey" href=""><i class="fal fa-plus-square"></i><span>Toon meer</span></a></div>
        <div class="more" style="display:none;">
            <?php foreach (array_slice($facetValues,8) as $facetValue):
                $escapedValue = $escapeAttr($facetValue['value']);
                $escapedId = $name . '[]' . $escapedValue;
                $label = $displayCount
                    ? sprintf('%s (<span class="count">%d</span>)', $escape($facetValue['label']),  $facetValue['count'])
                    : $escape($facetValue['label']);
            ?>
            <li class="search-facet-item">
                <input type="checkbox" name="facet[<?= $name ?>][]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
                <label for="<?= $escapedId ?>"><?= $label ?></label>
            </li>
            <?php endforeach; ?>
            <div class="less-link"><a class="has-text-grey" href=""><i class="fal fa-minus-square"></i><span>Toon minder</span></a></div>
        </div> 
    <?php endif;?>    
</ul>