<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchPage->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetElements2 = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>


    <h3 class="is-5 title" style="margin:0rem 0 0.3rem 0"><?= $translate('Facetten') ?></h3>

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Actieve facetten') ?></h4>
    <ul class="search-facets-active">
        <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetValue): ?>
        <li><?= $facetActive($name, ['value' => $facetValue, 'count' => null], $options) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-top">
            <input type="submit" value="<?= $translate('Facetten toepassen') ?>"/>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <p><?= $translate('Geen facetten.') ?></p>
        <?php else: ?>
            <ul class="search-facets-list">
                <?php foreach ($facets as $name => $facetValues): ?>           
                <li class="search-facet"> 
                    <h4 class="is-6 title" style="margin:1rem 0 0.3rem 0"><?= $translate($facetLabel($name)) ?></h4>                                 
                    <?= $facetElements($name, $facetValues, $options); ?>              
                </li>
                <?php endforeach; ?>            
            </ul>
        <?php endif; ?>
        <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-bottom">
            <input type="submit" value="<?= $translate('Facetten toepassen') ?>"/>
        </div>
        <?php endif; ?>

    </form>


<script>
    $(document).ready(function(){
        $( ".more-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().hide();
            $(this).parent().next( "div" ).show();
        });
        $( ".less-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().parent().hide();
            $(this).parent().parent().prev( ".more-link" ).show();
        });
    });
</script>