<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation|null $itemSet
 */

if (!isset($response)) return;

$searchFacets = $searchConfig->subSetting('facet', 'facets', []);
if (!count($searchFacets)) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$isFacetModeButton = !in_array($searchConfig->subSetting('facet', 'mode'), ['link', 'js']);
$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);
$displayRefine = (bool) $searchConfig->subSetting('facet', 'display_refine', true);
$labelRefine = $displayRefine ? $searchConfig->subSetting('facet', 'label_refine', 'Refine search') : null;
$displayFacetButton = $isFacetModeButton && ($displayActive || !empty($facets));
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', 'Apply facets') : null;
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', 'Reset facets') : null;

$facetActives = $plugins->get('facetActives');
$facetElements = $plugins->get('facetElements');

// TODO Remove item sets facets early when item set redirects to search.
// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet', []);
$i = 0;


$lang = $this->lang();
if($lang == "nl-NL"):
    $search = "Zoeken in filter";
else:
    $search = "Search in filter";  
endif;    
?>

<aside id="search-facets" class="facets">

    <?php if ($label = $searchConfig->subSetting('facet', 'label', 'Facets')): ?>
        <h3><?= $translate('Facets') ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
        <h4><?= $translate('Active facets') ?></h4>
        <?= $facetActives(null, $activeFacets, $searchConfig->setting('facet')) ?>
    <?php endif; ?>

    <form id="form-facets">
        <?php if ($displayFacetButton): ?>
            <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'refine', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'above' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
            <div class="facets-actions facets-actions-top">
                <?php if ($displayButtonSubmit): ?>
                    <input id="facets-apply" type="submit" value="<?= $escape($translate($labelSubmit)) ?>" class="btn btn-ghost-inv"/>
                <?php endif; ?>
                <?php if ($displayButtonReset): ?>
                    <input id="facets-reset" type="reset" value="<?= $escape($translate($labelReset)) ?>" class="btn btn-ghost-inv"/>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <?php if ($label = $searchConfig->subSetting('facet', 'label_no_facets', 'No facets')): ?>
            <p><?= $escape($translate($label)) ?></p>
        <?php endif; ?>
        <?php else: ?>
        <ul class="facets-list search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
                <?php $i++;?>
                <?php $facetParams = $searchFacets[$name]; ?>
                <?php $hasState = in_array($facetParams['state'] ?? '', ['expand', 'collapse', 'collapse_unless_set']); ?>
                <li class="search-facet facet<?= empty($facetParams['attributes']['class']) ? '' : ' ' . $escapeAttr($facetParams['attributes']['class']) ?>">
                    <details>
                        <?php if(count($facetValues) > 10):?>
                        <input type="text" id="facetSearch<?php echo $i;?>" oninput="searchFacet(<?php echo $i;?>)" placeholder="<?= $search ?>" style="margin:5% 0%;">
                        <?php endif;?>
                        <summary>
                            <h4><?= $escape($translate($facetParams['label'] ?? $name)) ?></h4>
                        </summary>
                        <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
                        <?= $facetSelect($name, $facetValues, $options) ?>
                        <?php else: ?>
                        <?= $facetElements($name, $facetValues, $options) ?>
                        <?php endif; ?>
                    </details>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'below' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
            <div class="facets-actions facets-actions-bottom">
                <?php if ($displayButtonSubmit): ?>
                <button id="facets-apply" class="button facets-apply" type="submit"><?= $escape($translate($labelSubmit)) ?></button>
                <?php endif; ?>
                <?php if ($displayButtonReset): ?>
                <button id="facets-reset" class="button facets-reset" type="reset"><?= $escape($translate($labelReset)) ?></button>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </form>
</aside>
<script>
 $(document).ready(function(){
    $( ".more-link a" ).click(function(e) {
        e.preventDefault();
        $(this).parent().hide();
        $(this).parent().next( "div" ).show();
    });
     $( ".less-link a" ).click(function(e) {
        e.preventDefault();
        $(this).parent().parent().hide();
        $(this).parent().parent().prev( ".more-link" ).show();
    });
});
function searchFacet(facet) {
  // Declare variables
  var input, filter, ul, li, label, i, txtValue;
  input = document.getElementById('facetSearch' + facet);
  filter = input.value.toUpperCase();
  details = input.parentElement;
  ul = details.getElementsByTagName('ul')[0];
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    label = li[i].getElementsByTagName("label")[0];
    txtValue = label.textContent || label.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>