<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchPage->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>

<style>
    li,ul{
        list-style-type: none;
    }
    details,summary{
        display: list-item;
    }
    h4{
        display:inline;
    }
    .apply-facets-top{
        padding-bottom: 5%;
    }
    .search-facet-items{
        overflow: auto;
        max-height: 150px;
    }
</style>

<aside class="search-facets">

    <h3><?= $translate('Facets') ?></h3>

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Active facets') ?></h4>
    <ul class="search-facets-active">
        <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetValue): ?>
        <li><?= $facetActive($name, ['value' => $facetValue, 'count' => null], $options) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-top">
            <input type="submit" value="<?= $translate('Apply facets') ?>"/>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?> 
        <p><?= $translate('No facets.') ?></p>
        <?php else: ?>
        <ul class="search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
            <li class="search-facet">
            <details>
                    <?php if(count($facetValues) > 10):?>
                    <input type="text" id="facetSearch" oninput="searchFacet()" placeholder="Zoeken in filter..." style="margin:5% 0%;">
                    <?php endif;?>
                    <summary>
                        <h4><?= $translate($facetLabel($name)) ?></h4>
                    </summary>
                    <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
                    <?= $facetSelect($name, $facetValues, $options) ?>
                    <?php else: ?>
                    <?= $facetElements($name, $facetValues, $options) ?>
                    <?php endif; ?>
                </details>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-bottom">
            <input type="submit" value="<?= $translate('Apply facets') ?>"/>
        </div>
        <?php endif; ?>

    </form>

</aside>

<script>
 $(document).ready(function(){
    $( ".more-link a" ).click(function(e) {
        e.preventDefault();
        $(this).parent().hide();
        $(this).parent().next( "div" ).show();
    });
     $( ".less-link a" ).click(function(e) {
        e.preventDefault();
        $(this).parent().parent().hide();
        $(this).parent().parent().prev( ".more-link" ).show();
    });
});
function searchFacet() {
  // Declare variables
  var input, filter, ul, li, label, i, txtValue;
  input = document.getElementById('facetSearch');
  filter = input.value.toUpperCase();
  details = input.parentElement;
  ul = details.getElementsByTagName('ul')[0];
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    label = li[i].getElementsByTagName("label")[0];
    txtValue = label.textContent || label.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>