<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var string $title
 * @var string $resourceName
 * @var string $resultPart
 */
$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$translatePlural = $plugins->get('translatePlural');

 // Default values of the module.
$displayParts = [
    'search_filters' => 'header',
    'paginator' => 'header',
    'per_pages' => 'header',
    'sort' => 'header',
    'grid_list' => 'header',
    'grid_list_mode' => 'auto',
];
$displayParts = $searchPage ? $searchPage->setting('display', $displayParts) : $displayParts;
$displayParts = array_filter($displayParts, function ($v) use ($resultPart) { return in_array($v, [$resultPart, 'both']); });

$resources = $response->getResources($resourceName);
// A check is done: when page is not first, the resources may be empty even with results.
if (!$resources) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnailHelper = $plugins->get('thumbnail');

$setting = $plugins->get($site ? 'siteSetting' : 'setting');

$filterLocale = (bool) $setting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;
$langValue = $filterLocale ? [$siteLang, ''] : null;

$headingTerm = $setting('browse_heading_property_term');
$bodyTerm = $setting('browse_body_property_term');

$gridListMode = $searchPage ? $searchPage->subSetting('display', 'grid_list_mode', 'auto') : 'auto';

$defaultThumbnail = '<img src="' . $assetUrl('thumbnails/default.png', 'Omeka', true) . '" title="' . $translate('No media') . '"/>';
?>

<div class="row">
<?php if ($title): ?>
<div class="col">
<h3 style="padding: 10px 16px;"><?= $escape($title) ?></h3>
</div>
<?php endif; ?>
<?php if (isset($displayParts['sort']) && $sortFields = $searchPage->subSetting('sort', 'fields')): ?>
<?= $this->searchSortSelector($query, $sortFields) ?>
<?php endif; ?>
</div>
<ul class="resource-list search-results-list grid" style="padding:0;margin:0;">
    <?php /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource */
    foreach ($resources as $resource):
        $resourceType = $resource->resourceName();
        $media = $resource->primaryMedia();
        $thumbnail = $media ? $thumbnailHelper($media, 'large') : $defaultThumbnail;
        $heading = $headingTerm ? $resource->value($headingTerm, ['lang' => $langValue]) : null;
        $heading = $heading ? $heading->asHtml() : $escape($resource->displayTitle($translate('[Untitled]'), $lang));
        $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $langValue]) : null;
        $body = $body ? $body->asHtml() : $escape($resource->displayDescription(null, $lang));
    ?>

    <li class="resource <?= $resourceType ?>">
        <div class="resource-thumbnail" style="border: solid #d4e7f3;">
            <?= $hyperlink->raw($thumbnail, $resource->url(), ['class' => 'resource-link']) ?>
        </div>
        <div class="resource-metadata" style="text-align:center;">
            <h4><?= $resource->linkRaw($heading) ?></h4>
            <div class="description">
                <?= $body ?>
            </div>
        </div>
    </li>

    <?php endforeach; ?>
</ul>