<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\MainSearchForm $form
 */

// Scripts are loaded via an event on view.layout and can be managed in search-form-main-header.phtml.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();


$reset = null;
$submit = null;
if ($form->has('form-reset')) {
    $reset = $form->get('form-reset');
    $form->remove('form-reset');
}
if ($form->has('submit')) {
    $submit = $form->get('submit');
    $form->remove('submit');
}
?>

<div id="advanced-search-form-wrapper">
    <div id="advanced-search-form">
        <?= $this->form()->openTag($form) ?>
        <?= $this->formCollection($form) ?>
        <div class="search-form-buttons">
            <?= $reset ? $this->formButton($reset) : null ?>
            <?= $submit ? '<button type="submit"><i class="material-icons">search</i></button>' : null ?>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
