<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <li><a href="<?php echo $site->url()."/objects?q=";?>">Catalogue</a></li>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8">
        <h1 class="title is-2 is-family-secondary"><?php echo $item->displayTitle(); ?></h1>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-6">
        <?php if (!$embedMedia && $itemMedia): ?>
             <div class="slider-for">
               <?php foreach($itemMedia as $media):?>
                 <div class="has-text-centered">
                   <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
                   <img src="<?php echo $url;?>">
                 </div>
               <?php endforeach;?>
             </div>
             <!--<div class="slider-nav" role="toolbar">
               <?php foreach($itemMedia as $media):?>
                   <?php $url = str_replace('http:', '', $media->thumbnailUrl('square'));?>
                   <img src="<?php echo $url;?>">
               <?php endforeach;?>
             </div>-->

          <?php endif; ?>
          <!--<h3><?php echo $translate('Item'); ?></h3>-->
          <?php $this->trigger('view.show.before'); ?>
          <?php if ($embedMedia && $itemMedia): ?>
              <div class="media-embeds">
              <?php foreach ($itemMedia as $media):
                  echo $media->render();
              endforeach;
              ?>
              </div>
          <?php endif; ?>
        </div>
        <div class="column is-6">
          <div class="metadata-box">
            <?php echo $item->displayValues(); ?>
            <?php $itemSets = $item->itemSets(); ?>
            <?php if (count($itemSets) > 0): ?>
              <div class="columns">
                <div class="column is-one-fifth">
                  <h4 class="title is-6">Collections</h4>
                </div>
                <div class="column is-three-fifths">
                  <?php foreach ($itemSets as $itemSet): ?>
                  <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                  <?php endforeach; ?>
                </div>
              </div>
            <?php endif; ?>
            </div>
          </div>
      </div>
  </div>
</section>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      fade: true,
      centerMode: true
    });
    /*$('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });*/
  });
</script>
