<?php
$translate = $this->plugin('translate');
$latest = $this->resources[0];
?>

<section class="section browse-preview">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php if($latest->displayTitle()):?>
                <h2><?php echo $latest->displayTitle();?></h2>
                <?php endif;?>
                <?php
                $itemMedia = $latest->media();
                $sortedMedia = $this->sortMedia($itemMedia);
                if (isset($sortedMedia['lightMedia'])):
                    echo $this->lightGalleryOutput($sortedMedia['lightMedia']);
                endif;
                ?>
            </div>
        </div>
    </div>
</section>