<?php
$translate = $this->plugin('translate');
$latest = $this->resources[0];
?>

<section class="section">
    <div class="container">
        <div class="row">
            <?php if($html):?>
            <div class="col-md-4">
                <div class="card card-gray" style="margin-bottom: 0px;">
                    <div class="card-body">
                    <?php if ($this->heading): ?>
                    <div class="card-title">
                        <h2><?php echo $this->heading; ?></h2>
                    </div>
                    <?php endif; ?>
                    <?php if ($this->html): ?>
                        <?php echo $this->html; ?>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endif;?>
            <div class="col-md-<?php if($html):?>8<?php else:?>12<?php endif;?>">
                <?php if($latest->displayTitle()):?>
                <h2><?php echo $latest->displayTitle();?></h2>
                <?php endif;?>
                <?php
                $itemMedia = $latest->media();
                $sortedMedia = $this->sortMedia($itemMedia);
                if (isset($sortedMedia['lightMedia'])):
                    echo $this->lightGalleryOutput($sortedMedia['lightMedia']);
                endif;
                ?>
            </div>
        </div>
    </div>
</section>