<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemSetRepresentation[] $itemSets
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');

$defaultThumbnail = $this->assetUrl('thumbnails/default.png', 'Omeka', true);
$defaultThumbnail = '<img src="' . $defaultThumbnail . '"/>';

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
$itemSetsTitles = [];
foreach ($itemSets as $itemSet):
    $itemSetsTitles[] = $itemSet->displayTitle();
endforeach;

asort($itemSetsTitles);
array_multisort($itemSets, $itemSetsTitles);

// foreach ($itemSetsTitles as $itemSetsTitle):
//     echo $itemSetsTitle;
//     echo ' ';
// endforeach;
?>

<!-- <div class="block item-set-showcase">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php
    foreach ($itemSets as $itemSet):
        $render = null;
        $title = null;
        $link = null;

        $itemSetThumbnail = $thumbnail($itemSet, $thumbnailType) ?: $defaultThumbnail;
        $render = $itemSet->linkRaw($itemSetThumbnail);

        if ($showTitleOption !== 'no_title'):
            $title = $itemSet->displayTitle(null, $lang);
            $link = $itemSet->link($title);
        endif;
    ?>
    <div class="item-set resource">
        <?= $render ?>
        <?= $link ?>
        <div class="caption">
            <?= $itemSet->displayDescription(null, $lang) ?>
        </div>
    </div>
    <?php endforeach; ?>
</div> -->
<style>
    .card-hover:hover{
        transform:translateY(-5px);
    }
</style>
<section class="section">
    <div class="container">
        <?php foreach ($itemSets as $itemSet):
            $itemSetTitle = $itemSet->displayTitle();
            $itemSetId = $itemSet->id();
            $items = $this->api()->search("items", ["item_set_id" => $itemSetId])->getContent();
        ?>
        <h2><?php echo $itemSetTitle;?></h2>
        <div class="row">
            <?php foreach($items as $item):
                $media = $item->media();
                $thumbnail = $media[0]->thumbnailUrl('large');   
                if ($mediaUrlOption !== 'no_media_url'){
                    $url = $media[0]->url();
                } else {
                    $url = $item->url();
                }
            ?>
            <div class="col-md-3">
                <div class="kul-card-image card card-gray card-hover" style="box-shadow:0.4em 0.4em slategray;">
                    <a href="<?php echo $url;?>">
                        <!-- <div class="card-img-top" style="background-image: url(<?php echo $thumbnail;?>);border:5px solid #d4e7f3;"></div> -->
                        <img src="<?php echo $thumbnail;?>" style="border:5px solid #d4e7f3;">
                    </a>
                    <div class="card-body">
                        <h5><?php echo $item->displayTitle();?></h5>
                    </div>
                </div>
            </div>
            <?php endforeach;?>
        </div>
        <?php endforeach;?>
    </div>
</section>