<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);

?>

    <?php
    $nav = $site->publicNav();
    $container = $nav->getContainer();
    $activePage = $nav->findActive($container);
    $type = $this->pageMetadata('type',$page) ?: null;
    $next = $this->pageMetadata('next',$page) ?: null;
    $previous = $this->pageMetadata('previous',$page) ?: null;

    if ($activePage):
      ?>
      <section class="section breadcrumb-section">
        <div class="container">
          <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li><a href="<?php echo $site->url();?>">Home</a></li>
              <?php $bc = $nav->breadcrumbs()->setSeparator('</li><li>')."";?>
                <?php if($bc):?>
                  <li><?php echo $nav->breadcrumbs()->setSeparator('</li><li>'); ?></li>
                <?php else:?>
                  <li><?php echo $page->title(); ?></li>
                <?php endif;?>
            </ul>
          </nav>
        </div>
      </section>

    <?php endif; ?>
<!--
<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>-->

<?php $this->trigger('view.show.before'); ?>
<?php echo $this->content; ?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php //echo $this->sitePagePagination(); ?>
<?php endif; ?>

<!--<?php if ($type == 'exhibit'): ?>
  <div class="column is-3">
    <div class="exhibit-nav">
    <?php $nav = $this->pageMetadata("exhibit_nav");?>
    <?php echo $this->navigation($nav)->menu();?>
    </div>
  </div>
<?php endif; ?>
</div>-->
    <div class="has-text-centered">
      <?php if($previous && ($this->pageMetadata('type',$previous) == 'exhibit_page' || $this->pageMetadata('type',$previous) == 'exhibit')):?>
        <a class="button" href="<?php echo $previous->url();?>">Previous</a>
      <?php endif;?>
      <?php if($next  && ($this->pageMetadata('type',$next) == 'exhibit_page'|| $this->pageMetadata('type',$next) == 'exhibit')):?>
        <a class="button" href="<?php echo $next->url();?>">Next</a>
      <?php endif;?>
    </div>
