<?php
$itemMedia = $resource->media();

foreach ($itemMedia as $media):
    if($media->mediaType() == "application/pdf") :
        $sortedMedia = [];
        $file = ["media" => $media];
        array_push($sortedMedia, $file);
        echo $this->lightGalleryOutput($sortedMedia);
    else: ?>
        <div class="media-embeds w-100">
            <?php echo $media->render(); ?>
        </div>
    <?php endif;?>
<?php endforeach; ?>